name: Test opening a pr vs main
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Install dependencies
        run: npm i
      - name: Build components using vite
        run: npm run build
      - name: Build storybook
        run: npm run build-storybook
